# The name of the workflow
# Testing new branch
name: build_test_and_deploy

# This workflow will run on any push to the repository
on:
  push

jobs:
  test:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      # Each step has a name, some code, and some options
      - name: Check out the repo
        uses: actions/checkout@v4 # This is a reference to some code to run

      # This step installs the Node version we want
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 5.0

      # Now we run our tests
      - name: Test with Jest, Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:test

  deploy:
      # Similar to docker, we set up a virtual machine to run our tests
      runs-on: ubuntu-latest
      needs: test
      
      steps:
          - name: Check out the repo
            uses: actions/checkout@v4
        
          - name: configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
              aws-region: eu-west-2
          
          - name: AWS deploy push to S3
            run: |
                aws deploy push \
                  --application-name luke-acebook \
                  --ignore-hidden-files \
                  --s3-location s3://luke-acebook/deployable-artifact.zip
                  --source .
          
          - name: Deploy to CodeDeploy
            run: |
                  aws deploy create-deployment \
                  --application-name luke-acebook \
                  --deployment-group luke-acebook \
                  --s3-location bucket=luke-acebook, key=deployable-artefact.zip,bundleType=zip